### ISSUE TITLE
Future of GoD Online

### ISSUE THREAD

**Issue by petaki** [galaxyofdrones/galaxyofdrones#17]
I have collected development ideas for discussion.

Before beta release:

- [x] Add an expedition system with global unit storage
- [x] Add the sum button to transport and movement
- [x] Add the PvE and PvP leaderboard
- [x] Add the global JS error handling (#23)
- [x] Add the shield system based on Solarion
- [x] Add the starter protection (#24)
- [x] Add attack monitor and radar
- [x] Add private messages
- [x] Display the positions of units on starmap
- [x] Enhance the mission system (#16)
- [x] Merge the capital and mothership storage
- [x] Show the numbers in tooltips (#11)

Before stable release:

- [ ] Add more tests to increase the stability
- [ ] Create an official website
- [ ] Write more documentations

After stable release:

- [ ] Add world events
- [ ] Add a way to cancel transport
- [ ] Add a layout manager to copy planet layouts
- [ ] Add enemy who returns from the single-player version
- [ ] Create an alliance system with common missions
- [ ] Design a multi server setup, where you can travel through the galaxies

**Comment by Chinese1904** [comment]
Maybe a platform for players to communicate would be nice as well - outside the alliance system.

**Comment by petaki** [comment]
@Chinese1904 Good idea, I added.

**Comment by isUndefined** [comment]
Please, add possibility to filter (show/hide) planets and show only personal. For ex. i want to send support on other planet and i cant find it in galaxy...

**Comment by edvordo** [comment]
Increase API throttling please :) Occupied some 15 planets and I'm hitting every third/forth planet -.-

**Comment by edvordo** [comment]
I'd welcome any of the following:

* a way to one-action (click or shortcut /see below/) upgrade all planet buildings
  * especially tiring when a player occupies several planets at once
* a way to one-action collect resources from all planets in the Mothership window
   * with specifying a minimum resource count ?
   * becomes a mundane task with having next to 100 planets
* some way to refresh the session of the signed in user
  * sometimes I get logged out of the API while I'm upgrading buildings on/collecting res. from planets
* better error handling, with focus on giving an information to the users what went wrong
  * kind of related to the previous point
* keyboard shortcuts for various things, e.g.: 
  * (construction window) `c` - constructs currently selected building
  * (construction window) `2`+`c` - selects a second building in the list and begins construction
  * (training window) autofocus to the field to set value^
  * `ctrl`+`t` - opens first drone factory with training availability (nothing if all are training)
  * (training window) `t` - train x selected units
  * (training window) `2` - selects a second unit in the list and focus to input to set amount, then ^
* canceling planet rename with the `ESC` key
* show a planet count on user profile
* auto-focus the select box with planets after planet name update

**Comment by edvordo** [comment]
More ideas:

* add a system of ,, "queueable" (?) actions .. what I mean by this is that let players to add various actions in queue, like maybe
  * when setting up a planet, let up build the whole layout and it would build when the things become available to build
  * or when training drones, queue say a series of 25 Goliath class ships to be trained
  * or send res to mothership if the res count on planet becomes greater than some number (configurable?)
* random drops, if you want them
  * maybe something like a meteor dropping on the planet and bringing few res with it, you'Đ have to send (a new kind of drone?) for
  * or maybe on the returning trips of Goliath class ships, they could pick up some resources
* add star harvesting
  * the stars are quire useless at this point, just sitting there, being able to be bookmarked, what if we had a new drone (ship? new kind of unit, say a "star harvester" that would just sit there untill called back?) that could harvest the stars for extra energy? or maybe a eith element?
* add a referral system
  * not quite sure what benefits would the referring person get out of referred players tho'

**Comment by edvordo** [comment]
And more

* allow for searching for an user on the leaderboards
* dismiss-able missions
  * for missions I do not and will not want to complete (those on the lower end of rewards)
* allow opening of the planets' `Sensor Tower` from starmap view
  * by clicking on either of the incoming or outgoing numbers/boxes in the left panel

**Comment by petaki** [comment]
@isUndefined The planets rendered as map tiles, therefore we cannot show/hide.

**Comment by petaki** [comment]
@edvordo Thanks for the suggestions, nice work :) I agree with many points.

Now I am working on a new feature which is related here. I would like to enhance the mothership, because it does not currently support the end game.

Therefore, I will add a new tab (Armory) to it where:

- You have training slots which will centralize the training
- Your slots number is equal to count of Drone Factories
- The trained units are stored here as long as they are sent to planets
- You can not send units back to mothership
- The travel time is instant to the capital planet
- You can move units with mothership between the planets

And you will get training missions besides mining.

**Comment by edvordo** [comment]
No problem, @petaki, I already have few more written down, just need to polish them for public view :) And I don't want to overwhelm you :D

Anyway, reading through that list you just posted:

* I'm really interested how the UI will handle hundreds of available slots (I have over 130 planets, each has several factories)
* With centralized training, we'll probably need a way to tell what units are already present on a given planet
* Not sure how moving units with Mothership will work, but I hope it doesn't mean i cannot shuffle units between planets without the need of the mothership. I mean, I know this probably won't happen often, once units are on a planet, they should stay there, BUT, I currently am in a process of reducing the Goliath count on some of my older planets by sending them to the new ones, there is still over 70 planets that have excess Goliaths :D Unless, of course, the travel time of the Mothership is reduced, then I could see it work
* Looking forward to new kind of missions 👍 

----------------------------------
Somewhat offtopic, for anyone interested, this is the current state of the galaxy. This screenshot shows (I believe) every single currently occupied planet (total count 686) in the game

![image](https://user-images.githubusercontent.com/6738779/36165163-e71f25b8-10ee-11e8-9a0e-ec8bd289fee8.png)

The color here is intentionally unified to not reveal unwanted (albeit still public) information 🙂

**Comment by edvordo** [comment]
Couple more ideas and/or suggestions (on but not only on (centralized) training)

* Please allow to auto-assign trained units to a planet
  * What I mean by this, allow for selecting a planet the queued batch is to be automatically sent to, ideally pre-selected to the planet I'm currently on. I'm certain I will not remember which planet I've trained the drones for when they finish in 2 weeks
* Not sure how possible this would be, but I'd welcome a change, that would spit out drones as they are trained
  * Currently, we have to wait for the entire batch to be trained, then and only then we get the drones we've set to train. This isn't much of a problem with small quantities, but when I queue a larger (like couple thousand Phoenix class ships) amount, it can take weeks to complete. Also a problem in case I'd want to switch to training some other units. Would be nice if got the units trained one by one, or idk in a batches of say 10, to lessen the load on the server.
  * Side note: This could (would!) be solved if we had [queqeable jobs](#issuecomment-364206313) :)
* [An overview of overall mining and production rates](https://user-images.githubusercontent.com/6738779/36299804-0588d532-12ff-11e8-8586-33b9d4be6cb0.png)

**Comment by dang-nabbit** [comment]
a general planet management window with info table would be nice

**Comment by edvordo** [comment]
Couple more things

* Similar to #8, add a way do destroy trained units/ships/drones
  * Currently the only way to get rid of ships you wouldn't want is to attack someone else that can withstand it and destroy them
* Add a way to cancel an ongoing transport
* Add level column to the rankings table
  * Side note: _**crossed level 1000 earlier today**_ 😀 
* On a similar note: Could we maybe get like multiple rankings categories? Ones that come into mind
  * Highest storage capacity
  * Highest unit count
  * Highest overall production
  * Highest # of missions completed (can be done recursively from mission logs)
  * Highest battles won / lost
  * XP gained today / yesterday
  * Building upgrades done today / yesterday / past week .. not sure which one ..
  * .. at this point I'd be just making stuff up, you get the point 🙂 
* Add basic stats (Attack, Defense /, Speed?/ ...) to Unit tooltips
  * When all my factories are training, there is no available info on what are the stats of individual units
* Expanding upion a thing I mentioned in [previous comment](#issuecomment-366353657), add an overview of
  * [used/overall unit/storage capacities](https://user-images.githubusercontent.com/6738779/36487569-893c42da-1721-11e8-9424-bf93bef988d4.png)
  * [overview of trained unit count](https://user-images.githubusercontent.com/6738779/36494445-52ce1d66-1732-11e8-9919-c3f8b15b128a.png)

_Some how I get a feeling I should give it a break :D For both of our sakes .._

**Comment by petaki** [comment]
@dang-nabbit Thanks for the suggestion!

The enhanced mothership will help the management of the planets.

@edvordo Awesome, thanks for the suggestions! :)

I would like to summarize a feature of the next update:

- I will add a new type of mission called Expeditions
- You will get randomly generated Expeditions to the stars
- You can do these with Icarus drones, but they will be destroyed in the heat of the sun
- If you will complete the expedition, you will get a Solarion (new resource)
- You can use the Solarion for instant Hyperjump

**Comment by edvordo** [comment]
No problem, my man :) Just throwing ideas out there for you to pick what you like :) Glad to see some stuck :D

I like the idea of new kind of mission, but to comment on anything else I'd have to see how exactly it'll work. Not entirely sure about the last point, I don't see myself moving the Mothership around a lot, it's fine where it is now and that has been the case for more than a month now. 🤷‍♂️

**Comment by edvordo** [comment]
Well, yesterday I was somewhat excited about the expeditions, they've had a bit overshot (I did expect a nerf), but reasonable XP rewards imho. Now when they'll give me around 4m XP, I don't see myself completing them, if only at random ..

**Comment by petaki** [comment]
@edvordo Yes, I tested two methods to nerf the values, because I wanted to reduce production time. But there will be no more expedition wipe.

**Comment by edvordo** [comment]
I actually think I like them where they are now :) Good job! 👍

**Comment by evan1024** [comment]
Have you thought about providing a guide for installing the project locally and starting to contribute? I'm looking for an open-source Laravel project to help out with and this looks perfect!

**Comment by edvordo** [comment]
@evan1024 There is [this](https://github.com/galaxyofdrones/docs) if you are interested in running in locally.

Worth a mention (that isn't in the Installation document) may be that it uses postgres database (or rather that's the one I used).

I can be ran on Apache as well, nginx is not a requirement.

**Comment by petaki** [comment]
I have created a trello board for handling these features.

https://trello.com/b/vWfdm6AA/galaxy-of-drones-online

**Comment by wumix** [comment]
Is there any way to install this game on a shared host

**Comment by edvordo** [comment]
With fair few changes, it may be .. plausible.

I haven't tried (obviously), but I'd imagine you'd
- install stuff locally because of composer and npm/yarn (no shared host will give you these)
- run the commands to build the database and generate the star map
- since you won't have access to redis, you'll need to figure out an alternative to [anything related to redis](https://github.com/galaxyofdrones/galaxyofdrones/search?q=redis&unscoped_q=redis) or [laravel-echo-server](https://github.com/galaxyofdrones/galaxyofdrones/search?q=echo&unscoped_q=echo)
  - for broadcasting you could swap to pusher
  - sessions the default handler might suffice
  - for queues, you can try [setting up a cron job to run](https://laracasts.com/discuss/channels/servers/database-queue-on-shared-hosting) them, but even if successful, you'll loose some accuracy, since crons can only run every minute minimum

Of course there is the downside, that you'll need to upload EVERYTHING necessary yourself via some (S)FTP connection

Also good luck getting updates to the project.

--------------

That being said ...

I believe it might be easier to just go for a virtual private server (VPS) and save yourself the hustle. They go for pretty much the same price as shared hosting do these days.

**Comment by wumix** [comment]
OK i will looking for an VPS

**Comment by iSimonL** [comment]
Latest result, the edge wher an old s2 galaxy witout graphic chip won't run it anymore. On pc perfect thoug, geforce gtx says, it's idle :D without the 25000 particles space cluter (only the planets) it also runs on older mobiles. https://www.youtube.com/watch?v=yhV1y1p2-U8

**Comment by wumix** [comment]
Hello, which prerequisites do I need for my vserver so that I can install galaxy of drones.

**Comment by Chris1904** [comment]
@wumix I am not too sure, but you should follow these instructions: https://github.com/galaxyofdrones/docs/blob/master/installation.md 

Seems like a basic Laravel development environment, so check out Laravel docs too.

**Comment by edvordo** [comment]
All the things form [here](https://laravel.com/docs/5.7/installation) + postgres and redis.

**Comment by wumix** [comment]
what i men is what server requirements my server need.
e.g Redis server NpM what more

**Comment by edvordo** [comment]
* PostreSQL
 * Redis (used for cache, session, queues)
 * nginx, but can be ran with Apache2 as well
 * PHP v >= 7.1.3 /w [these exts](https://laravel.com/docs/5.7/installation#server-requirements)
 * composer

**Comment by wumix** [comment]
okay and npm right?

**Comment by edvordo** [comment]
You compile the javascript and css locally, and it is [in the repo](https://github.com/galaxyofdrones/galaxyofdrones/tree/master/public), you don't need npm on the server itself.

**Comment by petaki** [comment]
Now you can use the dockerized version: https://github.com/galaxyofdrones/docker
